/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerrainRouteImport } from './routes/terrain'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ClientRouteImport } from './routes/client'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ClientRendezVousRouteImport } from './routes/client.rendez-vous'
import { Route as ClientPrestationsRouteImport } from './routes/client.prestations'
import { Route as ClientInterventionsRouteImport } from './routes/client.interventions'
import { Route as ClientFlotteRouteImport } from './routes/client.flotte'
import { Route as ClientFacturesRouteImport } from './routes/client.factures'
import { Route as ClientDocumentsRouteImport } from './routes/client.documents'
import { Route as AdminVehiculesRouteImport } from './routes/admin.vehicules'
import { Route as AdminRendezVousRouteImport } from './routes/admin.rendez-vous'
import { Route as AdminInterventionsRouteImport } from './routes/admin.interventions'
import { Route as AdminFacturationRouteImport } from './routes/admin.facturation'
import { Route as AdminEquipeRouteImport } from './routes/admin.equipe'
import { Route as AdminDemandesRdvRouteImport } from './routes/admin.demandes-rdv'
import { Route as AdminDemandesGelRouteImport } from './routes/admin.demandes-gel'
import { Route as AdminContratsRouteImport } from './routes/admin.contrats'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as TerrainInterventionIdRouteImport } from './routes/terrain.intervention.$id'
import { Route as ClientFlotteIdRouteImport } from './routes/client.flotte.$id'
import { Route as ClientContratsIdRouteImport } from './routes/client.contrats.$id'
import { Route as AdminVehiculesIdRouteImport } from './routes/admin.vehicules.$id'
import { Route as AdminInterventionsIdRouteImport } from './routes/admin.interventions.$id'
import { Route as AdminContratsIdRouteImport } from './routes/admin.contrats.$id'
import { Route as AdminClientsIdRouteImport } from './routes/admin.clients.$id'
import { Route as ClientImpactRouteImport } from './routes/client.impact'
import { Route as AdminImpactRouteImport } from './routes/admin.impact'

const TerrainRoute = TerrainRouteImport.update({
  id: '/terrain',
  path: '/terrain',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ClientRendezVousRoute = ClientRendezVousRouteImport.update({
  id: '/rendez-vous',
  path: '/rendez-vous',
  getParentRoute: () => ClientRoute,
} as any)
const ClientPrestationsRoute = ClientPrestationsRouteImport.update({
  id: '/prestations',
  path: '/prestations',
  getParentRoute: () => ClientRoute,
} as any)
const ClientInterventionsRoute = ClientInterventionsRouteImport.update({
  id: '/interventions',
  path: '/interventions',
  getParentRoute: () => ClientRoute,
} as any)
const ClientFlotteRoute = ClientFlotteRouteImport.update({
  id: '/flotte',
  path: '/flotte',
  getParentRoute: () => ClientRoute,
} as any)
const ClientFacturesRoute = ClientFacturesRouteImport.update({
  id: '/factures',
  path: '/factures',
  getParentRoute: () => ClientRoute,
} as any)
const ClientDocumentsRoute = ClientDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ClientRoute,
} as any)
const AdminVehiculesRoute = AdminVehiculesRouteImport.update({
  id: '/vehicules',
  path: '/vehicules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRendezVousRoute = AdminRendezVousRouteImport.update({
  id: '/rendez-vous',
  path: '/rendez-vous',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInterventionsRoute = AdminInterventionsRouteImport.update({
  id: '/interventions',
  path: '/interventions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacturationRoute = AdminFacturationRouteImport.update({
  id: '/facturation',
  path: '/facturation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquipeRoute = AdminEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDemandesRdvRoute = AdminDemandesRdvRouteImport.update({
  id: '/demandes-rdv',
  path: '/demandes-rdv',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDemandesGelRoute = AdminDemandesGelRouteImport.update({
  id: '/demandes-gel',
  path: '/demandes-gel',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContratsRoute = AdminContratsRouteImport.update({
  id: '/contrats',
  path: '/contrats',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const TerrainInterventionIdRoute = TerrainInterventionIdRouteImport.update({
  id: '/intervention/$id',
  path: '/intervention/$id',
  getParentRoute: () => TerrainRoute,
} as any)
const ClientFlotteIdRoute = ClientFlotteIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientFlotteRoute,
} as any)
const ClientContratsIdRoute = ClientContratsIdRouteImport.update({
  id: '/contrats/$id',
  path: '/contrats/$id',
  getParentRoute: () => ClientRoute,
} as any)
const AdminVehiculesIdRoute = AdminVehiculesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminVehiculesRoute,
} as any)
const AdminInterventionsIdRoute = AdminInterventionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminInterventionsRoute,
} as any)
const AdminContratsIdRoute = AdminContratsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminContratsRoute,
} as any)
const AdminClientsIdRoute = AdminClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminClientsRoute,
} as any)
const ClientImpactRoute = ClientImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => ClientRoute,
} as any)
const AdminImpactRoute = AdminImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/login': typeof LoginRoute
  '/terrain': typeof TerrainRouteWithChildren
  '/admin/clients': typeof AdminClientsRouteWithChildren
  '/admin/contrats': typeof AdminContratsRouteWithChildren
  '/admin/demandes-gel': typeof AdminDemandesGelRoute
  '/admin/demandes-rdv': typeof AdminDemandesRdvRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/facturation': typeof AdminFacturationRoute
  '/admin/impact': typeof AdminImpactRoute
  '/admin/interventions': typeof AdminInterventionsRouteWithChildren
  '/admin/rendez-vous': typeof AdminRendezVousRoute
  '/admin/vehicules': typeof AdminVehiculesRouteWithChildren
  '/client/documents': typeof ClientDocumentsRoute
  '/client/factures': typeof ClientFacturesRoute
  '/client/impact': typeof ClientImpactRoute
  '/client/flotte': typeof ClientFlotteRouteWithChildren
  '/client/interventions': typeof ClientInterventionsRoute
  '/client/prestations': typeof ClientPrestationsRoute
  '/client/rendez-vous': typeof ClientRendezVousRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
  '/admin/contrats/$id': typeof AdminContratsIdRoute
  '/admin/interventions/$id': typeof AdminInterventionsIdRoute
  '/admin/vehicules/$id': typeof AdminVehiculesIdRoute
  '/client/contrats/$id': typeof ClientContratsIdRoute
  '/client/flotte/$id': typeof ClientFlotteIdRoute
  '/terrain/intervention/$id': typeof TerrainInterventionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/terrain': typeof TerrainRouteWithChildren
  '/admin/clients': typeof AdminClientsRouteWithChildren
  '/admin/contrats': typeof AdminContratsRouteWithChildren
  '/admin/demandes-gel': typeof AdminDemandesGelRoute
  '/admin/demandes-rdv': typeof AdminDemandesRdvRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/facturation': typeof AdminFacturationRoute
  '/admin/impact': typeof AdminImpactRoute
  '/admin/interventions': typeof AdminInterventionsRouteWithChildren
  '/admin/rendez-vous': typeof AdminRendezVousRoute
  '/admin/vehicules': typeof AdminVehiculesRouteWithChildren
  '/client/documents': typeof ClientDocumentsRoute
  '/client/factures': typeof ClientFacturesRoute
  '/client/impact': typeof ClientImpactRoute
  '/client/flotte': typeof ClientFlotteRouteWithChildren
  '/client/interventions': typeof ClientInterventionsRoute
  '/client/prestations': typeof ClientPrestationsRoute
  '/client/rendez-vous': typeof ClientRendezVousRoute
  '/admin': typeof AdminIndexRoute
  '/client': typeof ClientIndexRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
  '/admin/contrats/$id': typeof AdminContratsIdRoute
  '/admin/interventions/$id': typeof AdminInterventionsIdRoute
  '/admin/vehicules/$id': typeof AdminVehiculesIdRoute
  '/client/contrats/$id': typeof ClientContratsIdRoute
  '/client/flotte/$id': typeof ClientFlotteIdRoute
  '/terrain/intervention/$id': typeof TerrainInterventionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/login': typeof LoginRoute
  '/terrain': typeof TerrainRouteWithChildren
  '/admin/clients': typeof AdminClientsRouteWithChildren
  '/admin/contrats': typeof AdminContratsRouteWithChildren
  '/admin/demandes-gel': typeof AdminDemandesGelRoute
  '/admin/demandes-rdv': typeof AdminDemandesRdvRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/admin/facturation': typeof AdminFacturationRoute
  '/admin/impact': typeof AdminImpactRoute
  '/admin/interventions': typeof AdminInterventionsRouteWithChildren
  '/admin/rendez-vous': typeof AdminRendezVousRoute
  '/admin/vehicules': typeof AdminVehiculesRouteWithChildren
  '/client/documents': typeof ClientDocumentsRoute
  '/client/factures': typeof ClientFacturesRoute
  '/client/impact': typeof ClientImpactRoute
  '/client/flotte': typeof ClientFlotteRouteWithChildren
  '/client/interventions': typeof ClientInterventionsRoute
  '/client/prestations': typeof ClientPrestationsRoute
  '/client/rendez-vous': typeof ClientRendezVousRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
  '/admin/contrats/$id': typeof AdminContratsIdRoute
  '/admin/interventions/$id': typeof AdminInterventionsIdRoute
  '/admin/vehicules/$id': typeof AdminVehiculesIdRoute
  '/client/contrats/$id': typeof ClientContratsIdRoute
  '/client/flotte/$id': typeof ClientFlotteIdRoute
  '/terrain/intervention/$id': typeof TerrainInterventionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/client'
    | '/login'
    | '/terrain'
    | '/admin/clients'
    | '/admin/contrats'
    | '/admin/demandes-gel'
    | '/admin/demandes-rdv'
    | '/admin/equipe'
    | '/admin/facturation'
    | '/admin/impact'
    | '/admin/interventions'
    | '/admin/rendez-vous'
    | '/admin/vehicules'
    | '/client/documents'
    | '/client/factures'
    | '/client/flotte'
    | '/client/impact'
    | '/client/interventions'
    | '/client/prestations'
    | '/client/rendez-vous'
    | '/admin/'
    | '/client/'
    | '/admin/clients/$id'
    | '/admin/contrats/$id'
    | '/admin/interventions/$id'
    | '/admin/vehicules/$id'
    | '/client/contrats/$id'
    | '/client/flotte/$id'
    | '/terrain/intervention/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/terrain'
    | '/admin/clients'
    | '/admin/contrats'
    | '/admin/demandes-gel'
    | '/admin/demandes-rdv'
    | '/admin/equipe'
    | '/admin/facturation'
    | '/admin/impact'
    | '/admin/interventions'
    | '/admin/rendez-vous'
    | '/admin/vehicules'
    | '/client/documents'
    | '/client/factures'
    | '/client/flotte'
    | '/client/impact'
    | '/client/interventions'
    | '/client/prestations'
    | '/client/rendez-vous'
    | '/admin'
    | '/client'
    | '/admin/clients/$id'
    | '/admin/contrats/$id'
    | '/admin/interventions/$id'
    | '/admin/vehicules/$id'
    | '/client/contrats/$id'
    | '/client/flotte/$id'
    | '/terrain/intervention/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/client'
    | '/login'
    | '/terrain'
    | '/admin/clients'
    | '/admin/contrats'
    | '/admin/demandes-gel'
    | '/admin/demandes-rdv'
    | '/admin/equipe'
    | '/admin/facturation'
    | '/admin/impact'
    | '/admin/interventions'
    | '/admin/rendez-vous'
    | '/admin/vehicules'
    | '/client/documents'
    | '/client/factures'
    | '/client/flotte'
    | '/client/impact'
    | '/client/interventions'
    | '/client/prestations'
    | '/client/rendez-vous'
    | '/admin/'
    | '/client/'
    | '/admin/clients/$id'
    | '/admin/contrats/$id'
    | '/admin/interventions/$id'
    | '/admin/vehicules/$id'
    | '/client/contrats/$id'
    | '/client/flotte/$id'
    | '/terrain/intervention/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  LoginRoute: typeof LoginRoute
  TerrainRoute: typeof TerrainRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terrain': {
      id: '/terrain'
      path: '/terrain'
      fullPath: '/terrain'
      preLoaderRoute: typeof TerrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/client/rendez-vous': {
      id: '/client/rendez-vous'
      path: '/rendez-vous'
      fullPath: '/client/rendez-vous'
      preLoaderRoute: typeof ClientRendezVousRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/prestations': {
      id: '/client/prestations'
      path: '/prestations'
      fullPath: '/client/prestations'
      preLoaderRoute: typeof ClientPrestationsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/interventions': {
      id: '/client/interventions'
      path: '/interventions'
      fullPath: '/client/interventions'
      preLoaderRoute: typeof ClientInterventionsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/flotte': {
      id: '/client/flotte'
      path: '/flotte'
      fullPath: '/client/flotte'
      preLoaderRoute: typeof ClientFlotteRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/factures': {
      id: '/client/factures'
      path: '/factures'
      fullPath: '/client/factures'
      preLoaderRoute: typeof ClientFacturesRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/documents': {
      id: '/client/documents'
      path: '/documents'
      fullPath: '/client/documents'
      preLoaderRoute: typeof ClientDocumentsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/vehicules': {
      id: '/admin/vehicules'
      path: '/vehicules'
      fullPath: '/admin/vehicules'
      preLoaderRoute: typeof AdminVehiculesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rendez-vous': {
      id: '/admin/rendez-vous'
      path: '/rendez-vous'
      fullPath: '/admin/rendez-vous'
      preLoaderRoute: typeof AdminRendezVousRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/interventions': {
      id: '/admin/interventions'
      path: '/interventions'
      fullPath: '/admin/interventions'
      preLoaderRoute: typeof AdminInterventionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facturation': {
      id: '/admin/facturation'
      path: '/facturation'
      fullPath: '/admin/facturation'
      preLoaderRoute: typeof AdminFacturationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/impact': {
      id: '/admin/impact'
      path: '/impact'
      fullPath: '/admin/impact'
      preLoaderRoute: typeof AdminImpactRouteImport
      parentRoute: typeof AdminRoute
    }
    '/client/impact': {
      id: '/client/impact'
      path: '/impact'
      fullPath: '/client/impact'
      preLoaderRoute: typeof ClientImpactRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/equipe': {
      id: '/admin/equipe'
      path: '/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AdminEquipeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/demandes-rdv': {
      id: '/admin/demandes-rdv'
      path: '/demandes-rdv'
      fullPath: '/admin/demandes-rdv'
      preLoaderRoute: typeof AdminDemandesRdvRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/demandes-gel': {
      id: '/admin/demandes-gel'
      path: '/demandes-gel'
      fullPath: '/admin/demandes-gel'
      preLoaderRoute: typeof AdminDemandesGelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contrats': {
      id: '/admin/contrats'
      path: '/contrats'
      fullPath: '/admin/contrats'
      preLoaderRoute: typeof AdminContratsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/terrain/intervention/$id': {
      id: '/terrain/intervention/$id'
      path: '/intervention/$id'
      fullPath: '/terrain/intervention/$id'
      preLoaderRoute: typeof TerrainInterventionIdRouteImport
      parentRoute: typeof TerrainRoute
    }
    '/client/flotte/$id': {
      id: '/client/flotte/$id'
      path: '/$id'
      fullPath: '/client/flotte/$id'
      preLoaderRoute: typeof ClientFlotteIdRouteImport
      parentRoute: typeof ClientFlotteRoute
    }
    '/client/contrats/$id': {
      id: '/client/contrats/$id'
      path: '/contrats/$id'
      fullPath: '/client/contrats/$id'
      preLoaderRoute: typeof ClientContratsIdRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/vehicules/$id': {
      id: '/admin/vehicules/$id'
      path: '/$id'
      fullPath: '/admin/vehicules/$id'
      preLoaderRoute: typeof AdminVehiculesIdRouteImport
      parentRoute: typeof AdminVehiculesRoute
    }
    '/admin/interventions/$id': {
      id: '/admin/interventions/$id'
      path: '/$id'
      fullPath: '/admin/interventions/$id'
      preLoaderRoute: typeof AdminInterventionsIdRouteImport
      parentRoute: typeof AdminInterventionsRoute
    }
    '/admin/contrats/$id': {
      id: '/admin/contrats/$id'
      path: '/$id'
      fullPath: '/admin/contrats/$id'
      preLoaderRoute: typeof AdminContratsIdRouteImport
      parentRoute: typeof AdminContratsRoute
    }
    '/admin/clients/$id': {
      id: '/admin/clients/$id'
      path: '/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof AdminClientsIdRouteImport
      parentRoute: typeof AdminClientsRoute
    }
  }
}

interface AdminClientsRouteChildren {
  AdminClientsIdRoute: typeof AdminClientsIdRoute
}

const AdminClientsRouteChildren: AdminClientsRouteChildren = {
  AdminClientsIdRoute: AdminClientsIdRoute,
}

const AdminClientsRouteWithChildren = AdminClientsRoute._addFileChildren(
  AdminClientsRouteChildren,
)

interface AdminContratsRouteChildren {
  AdminContratsIdRoute: typeof AdminContratsIdRoute
}

const AdminContratsRouteChildren: AdminContratsRouteChildren = {
  AdminContratsIdRoute: AdminContratsIdRoute,
}

const AdminContratsRouteWithChildren = AdminContratsRoute._addFileChildren(
  AdminContratsRouteChildren,
)

interface AdminInterventionsRouteChildren {
  AdminInterventionsIdRoute: typeof AdminInterventionsIdRoute
}

const AdminInterventionsRouteChildren: AdminInterventionsRouteChildren = {
  AdminInterventionsIdRoute: AdminInterventionsIdRoute,
}

const AdminInterventionsRouteWithChildren =
  AdminInterventionsRoute._addFileChildren(AdminInterventionsRouteChildren)

interface AdminVehiculesRouteChildren {
  AdminVehiculesIdRoute: typeof AdminVehiculesIdRoute
}

const AdminVehiculesRouteChildren: AdminVehiculesRouteChildren = {
  AdminVehiculesIdRoute: AdminVehiculesIdRoute,
}

const AdminVehiculesRouteWithChildren = AdminVehiculesRoute._addFileChildren(
  AdminVehiculesRouteChildren,
)

interface AdminRouteChildren {
  AdminClientsRoute: typeof AdminClientsRouteWithChildren
  AdminContratsRoute: typeof AdminContratsRouteWithChildren
  AdminDemandesGelRoute: typeof AdminDemandesGelRoute
  AdminDemandesRdvRoute: typeof AdminDemandesRdvRoute
  AdminEquipeRoute: typeof AdminEquipeRoute
  AdminFacturationRoute: typeof AdminFacturationRoute
  AdminImpactRoute: typeof AdminImpactRoute
  AdminInterventionsRoute: typeof AdminInterventionsRouteWithChildren
  AdminRendezVousRoute: typeof AdminRendezVousRoute
  AdminVehiculesRoute: typeof AdminVehiculesRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClientsRoute: AdminClientsRouteWithChildren,
  AdminContratsRoute: AdminContratsRouteWithChildren,
  AdminDemandesGelRoute: AdminDemandesGelRoute,
  AdminDemandesRdvRoute: AdminDemandesRdvRoute,
  AdminEquipeRoute: AdminEquipeRoute,
  AdminFacturationRoute: AdminFacturationRoute,
  AdminImpactRoute: AdminImpactRoute,
  AdminInterventionsRoute: AdminInterventionsRouteWithChildren,
  AdminRendezVousRoute: AdminRendezVousRoute,
  AdminVehiculesRoute: AdminVehiculesRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientFlotteRouteChildren {
  ClientFlotteIdRoute: typeof ClientFlotteIdRoute
}

const ClientFlotteRouteChildren: ClientFlotteRouteChildren = {
  ClientFlotteIdRoute: ClientFlotteIdRoute,
}

const ClientFlotteRouteWithChildren = ClientFlotteRoute._addFileChildren(
  ClientFlotteRouteChildren,
)

interface ClientRouteChildren {
  ClientDocumentsRoute: typeof ClientDocumentsRoute
  ClientFacturesRoute: typeof ClientFacturesRoute
  ClientFlotteRoute: typeof ClientFlotteRouteWithChildren
  ClientImpactRoute: typeof ClientImpactRoute
  ClientInterventionsRoute: typeof ClientInterventionsRoute
  ClientPrestationsRoute: typeof ClientPrestationsRoute
  ClientRendezVousRoute: typeof ClientRendezVousRoute
  ClientIndexRoute: typeof ClientIndexRoute
  ClientContratsIdRoute: typeof ClientContratsIdRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientDocumentsRoute: ClientDocumentsRoute,
  ClientFacturesRoute: ClientFacturesRoute,
  ClientFlotteRoute: ClientFlotteRouteWithChildren,
  ClientImpactRoute: ClientImpactRoute,
  ClientInterventionsRoute: ClientInterventionsRoute,
  ClientPrestationsRoute: ClientPrestationsRoute,
  ClientRendezVousRoute: ClientRendezVousRoute,
  ClientIndexRoute: ClientIndexRoute,
  ClientContratsIdRoute: ClientContratsIdRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface TerrainRouteChildren {
  TerrainInterventionIdRoute: typeof TerrainInterventionIdRoute
}

const TerrainRouteChildren: TerrainRouteChildren = {
  TerrainInterventionIdRoute: TerrainInterventionIdRoute,
}

const TerrainRouteWithChildren =
  TerrainRoute._addFileChildren(TerrainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  LoginRoute: LoginRoute,
  TerrainRoute: TerrainRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
